[package]
name = "abstract-asm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
evaluator = { path = "../evaluator" }
util = { path = "../util" }
indexmap = "1.8.0"
strum_macros = "0.24"